apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgress-pod
      app: demo-voting-app
    template:
      metadata:
        name: postgress-pod
        labels:
          name: postgress-pod
          app: demo-voting-app
      spec:
        containers:
          - name: postgress
            image: postgress:9.4
            env:
              name: POSTGRES_USER
              value: "postgres"
              name: POSTGRES_PASSWORD
              value: "postgres"
            ports:
            - containerPort: 5432